### PR TITLE
fix: Mac os gui nits

### LINKED ISSUE #8012: Log visibility toggle does not work on macOS
### Project

Deskflow

### Deskflow version number

1.17.2.111

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [ ] Windows
- [x] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### OS versions/distros

- macOS 14.5

### What steps will reproduce the problem?

1. Run GUI
2. Click 'Log'

Expect: It hides
Actual: Nothing

### Additional information

Screenshot 2024-12-26 at 15 48 06

### PR DESCRIPTION
**Pull request by sithlord48**
- Fix show and activate on mac os (need showNormal after all)
 - make a duplicate quit action for the tray menu on mac os
 - Fixes #8012

### CODE REVIEW

File: src/apps/deskflow-gui/MainWindow.cpp [hunk 1]
```diff
@@ -527,9 +527,14 @@ void MainWindow::open()
   QList<QAction *> trayActions{m_actionStartCore, m_actionStopCore, nullptr, m_actionQuit};
 
 #ifdef Q_OS_MAC
+  // Duplicate quit needed for mac os tray menu
+  QAction *quit2 = new QAction(tr("Quit Deskflow"), this);
+  quit2->setShortcut(QKeySequence::Quit);
```
Comment (nbolton) [inline src/apps/deskflow-gui/MainWindow.cpp:532]:
```suggestion
  QAction *macQuit = new QAction(tr("Quit Deskflow"), this);
  macQuit->setShortcut(QKeySequence::Quit);
```

**Review by nbolton — COMMENTED** [review]
How about a more specific var name?

File: src/apps/deskflow-gui/MainWindow.cpp (hunk 1 above)
Comment (sithlord48) [reply src/apps/deskflow-gui/MainWindow.cpp:532]: ok fine ill use a better name :P

**Review by nbolton — APPROVED** [review]
