### PR TITLE
Retry mechanism for Windows Daemon IPC client

### LINKED ISSUE #8505: GUI intermittently fails to connect to Daemon
### Project

Deskflow

### Deskflow version info

Deskflow: 1.21.2.16 (50fb62ce)
Qt: 6.8.2
System: Windows 11 Version 24H2

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [x] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### OS versions/distros

Windows

### What steps will reproduce the problem?

1. Run Windows installer
2. Wait for GUI to run at end of install

Expected: GUI connects to daemon
Actual: Intermittently, the GUI will show the error 'There was a problem finding the Deskflow background service (daemon).'

Image

### Log output

Daemon
```
Deskflow Daemon v1.21.2.16 (50fb62ce)
[2025-04-18T07:28:03] DEBUG: log level: DEBUG
	C:\Projects\deskflow\src\apps\deskflow-daemon\deskflow-daemon.cpp:86
[2025-04-18T07:28:03] DEBUG: checking if process is elevated
	C:\Projects\deskflow\src\lib\arch\win32\ArchMiscWindows.cpp:529
[2025-04-18T07:28:03] DEBUG: process is elevated
	C:\Projects\deskflow\src\lib\arch\win32\ArchMiscWindows.cpp:549
[2025-04-18T07:28:03] DEBUG: ipc server listening on: deskflow-daemon
	C:\Projects\deskflow\src\lib\deskflow\ipc\DaemonIpcServer.cpp:40
[2025-04-18T07:28:03] NOTE: starting daemon
	C:\Projects\deskflow\src\lib\deskflow\DaemonApp.cpp:147
[2025-04-18T07:28:03] DEBUG: loaded sas.dll, used to simulate ctrl-alt-del
	C:\Projects\deskflow\src\lib\platform\MSWindowsWatchdog.cpp:563
[2025-04-18T07:28:03] DEBUG: found SendSAS function in sas.dll
	C:\Projects\deskflow\src\lib\platform\MSWindowsWatchdog.cpp:570
[2025-04-18T07:28:03] DEBUG: using last known command: C:/Projects/deskflow/build/bin-copy/deskflow-server.exe -f --debug DEBUG --name tuvok-win --stop-on-desk-switch --enable-crypto --disable-client-cert-check --address :24800 -c C:/ProgramData/Deskflow/deskflow-server.conf --tls-cert C:/ProgramData/Deskflow/tls/deskflow.pem
	C:\Projects\deskflow\src\lib\deskflow\DaemonApp.cpp:174
[2025-04-18T07:28:03] DEBUG: setting watchdog process config
	C:\Projects\deskflow\src\lib\platform\MSWindowsWatchdog.cpp:342
[2025-04-18T07:28:03] DEBUG: command changed, queueing process start
	C:\Projects\deskflow\src\lib\platform\MSWindowsWatchdog.cpp:350
[2025-04-18T07:28:03] DEBUG: starting daemon thread
	C:\Projects\deskflow\src\lib\deskflow\DaemonApp.cpp:179
[2025-04-18T07:28:03] DEBUG: daemon thread started
	C:\Projects\deskflow\src\lib\deskflow\DaemonApp.cpp:154
[2025-04-18T07:28:03] DEBUG: running daemon in background (daemonizing)
	C:\Projects\deskflow\src\lib\deskflow\DaemonApp.cpp:160
[2025-04-18T07:28:03] DEBUG: setting service status: state=2, step=0, waitHint=10000
	C:\Projects\deskflow\src\lib\arch\win32\ArchDaemonWindows.cpp:353
[2025-04-18T07:28:03] DEBUG: setting service status: state=4, step=0, waitHint=0
	C:\Projects\deskflow\src\lib\arch\win32\ArchDaemonWindows.cpp:353
[2025-04-18T07:28:03] DEBUG: adopting new buffer
	C:\Projects\deskflow\src\lib\base\EventQueue.cpp:154
[2025-04-18T07:28:03] DEBUG: starting watchdog threads
	C:\Projects\deskflow\src\lib\deskflow\DaemonApp.cpp:211
[2025-04-18T07:28:03] INFO: daemon is running
	C:\Projects\deskflow\src\lib\deskflow\DaemonApp.cpp:215
[2025-04-18T07:28:03] DEBUG: event queue is ready
```

GUI
```log
[2025-04-18T07:30:54] INFO: starting core server process (service mode)
	C:\Projects\deskflow\src\lib\gui\core\CoreProcess.cpp:336
[2025-04-18T07:30:54] INFO: core config file: C:/ProgramData/Deskflow/deskflow-server.conf
	C:\Projects\deskflow\src\lib\gui\core\CoreProcess.cpp:527
[2025-04-18T07:30:54] INFO: running command: C:/Projects/deskflow/build/bin-copy/deskflow-server.exe -f --debug DEBUG2 --name tuvok-win --stop-on-desk-switch --enable-crypto --disable-client-cert-check --address :24800 -c C:/ProgramData/Deskflow/deskflow-server.conf --tls-cert C:/ProgramData/Deskflow/tls/deskflow.pem
	C:\Projects\deskflow\src\lib\gui\core\CoreProcess.cpp:264
[2025-04-18T07:30:54] WARNING: daemon ipc client got empty response
	C:\Projects\deskflow\src\lib\gui\ipc\DaemonIpcClient.cpp:99
[2025-04-18T07:30:54] WARNING: daemon ipc client failed to send hello
	C:\Projects\deskflow\src\lib\gui\ipc\DaemonIpcClient.cpp:47
[2025-04-18T07:30:56] WARNING: daemon ipc client keep alive failed to connect
	C:\Projects\deskflow\src\lib\gui\ipc\DaemonIpcClient.cpp:122
[2025-04-18T07:30:56] WARNING: cannot start process, ipc command failed
	C:\Projects\deskflow\src\lib\gui\core\CoreProcess.cpp:267
```

### Additional information

The daemon is running, and is definitely listening for IPC connections. 

Although we're calling `m_socket->waitForBytesWritten` and `m_socket->waitForReadyRead`, there might be some sort of timing bug happening during the connection.

### PR DESCRIPTION
**Pull request by nbolton**
Fixes #8505

Todo:
- [x] Remove timeout change (ineffective)
- [x] Retry mechnaism for when hello back isn't received
- [x] Test for a few days to confirm the intermittent bug is fixed

### CODE REVIEW

File: src/lib/gui/ipc/DaemonIpcClient.cpp [hunk 1]
```diff
@@ -108,7 +135,7 @@ bool DaemonIpcClient::sendMessage(const QString &message, const QString &expectA
       return false;
     }
 
-    if (responseData != expectAck + "\n") {
+    if (responseData != expectAck + "x\n") {
```
Comment (sithlord48) [inline src/lib/gui/ipc/DaemonIpcClient.cpp:138]: double checking that this `x` is an expected change.

Comment (nbolton) [reply src/lib/gui/ipc/DaemonIpcClient.cpp:138]: This PR is a draft; it is not yet ready for review. Please review when I request your review.

**Review by sithlord48 — APPROVED** [review]
This looks ok to me.

**Comment by nbolton** [comment]
Skipping flaky openSUSE:
```
Repository 'Open H.264 Codec (openSUSE Tumbleweed)' is invalid.
[repo-openh[26](https://github.com/deskflow/deskflow/actions/runs/14730396370/job/41343003510?pr=8508#step:3:27)4|http://codecs.opensuse.org/openh264/openSUSE_Tumbleweed] Failed to retrieve new repository metadata.
History:
 - [|] Error trying to read from 'http://codecs.opensuse.org/openh264/openSUSE_Tumbleweed'
 - Download (curl) error for 'http://codecs.opensuse.org/openh264/openSUSE_Tumbleweed/repodata/repomd.xml':
   Error code: Connection failed
   Error message: Failed to connect to codecs.opensuse.org port 80 after 4001 ms: Could not connect to server
```
