### PR TITLE
fix: Settings dialog blocking return to Automatic

### LINKED ISSUE #9501: Can't change binding IP from specified back to auto
### Sanity checks

- [ ] I have done the sanity checks, and my issue persists
- [ ] These sanity checks are not relevant to the bug

### Deskflow version info

Deskflow: 1.26.0.13 (4c7f546c)
Qt: 6.9.3
System: Fedora Linux 42 (Workstation Edition)
Session: GNOME (wayland)

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [x] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Deskflow configuration

n/a

### What steps will reproduce the problem?

1. Change 'Network IP' to something other than auto

Image

2. Click 'Save'
3. Try to change it back to auto

Expected: Can save
Actual: Save disabled

Image

### Log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sithlord48**
## Description

ignore the interface changes being check as part of isModified when the settings was opened w/ the interface not set and its has not changed. 
 - Hide the Advanced tab on when portable windows 
## Disclosure of AI use

None
## Related Issue

fixes: #9501
## How Has This Been Tested?

Run play w/ interface settings.

### CODE REVIEW

File: src/lib/gui/dialogs/SettingsDialog.cpp [hunk 1]
```diff
@@ -32,7 +32,7 @@ SettingsDialog::SettingsDialog(QWidget *parent, const IServerConfig &serverConfi
   ui->setupUi(this);
 
   // no advanced options on macOS
```
Comment (amagus) [inline src/lib/gui/dialogs/SettingsDialog.cpp]: maybe the comment is now outdated?

Comment (sithlord48) [reply src/lib/gui/dialogs/SettingsDialog.cpp]: updated the commit.

**Review by amagus — APPROVED** [review]
Tested both changes, looks good.

**Review by nbolton — APPROVED** [review]
Fixed, thanks
