### PR TITLE
fix: check bsdpath for evdev fixes #8112

### LINKED ISSUE #8112: The location of evdev.xml is hard-coded and not compatible with FreeBSD
### Project

Deskflow

### Deskflow version number

1.18.0.86

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [x] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [x] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [x] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [x] I am unable to try the latest continuous build

### OS versions/distros

- FreeBSD 14.2-STABLE

### Deskflow configuration

- Deskflow server on FreeBSD
- Synergy 1 clients on Windows 11 and macOS Sequoia (iMac, mac mini, and MacBook Pro)

### What steps will reproduce the problem?

The path of evdev.xml is hard-coded as "/usr/share/X11/xkb/rules/evdev.xml". On FreeBSD, it should be "/usr/local/share/X11/xkb/rules/evdev.xml".
Due to that, the Deskflow server fails to recognize the host's language settings.

### Log output

```shell
[2025-01-20T09:44:09] INFO: starting core server process (desktop mode)
[2025-01-20T09:44:09] INFO: core config file: /home/kasahara/.config/Deskflow/deskflow-server.conf
[2025-01-20T09:44:09] INFO: running command: /usr/home/kasahara/src/deskflow/build/bin/deskflow-server -f --no-tray --debug INFO --name elvenbow --enable-crypto --address :24800 -c /home/kasahara/.config/Deskflow/deskflow-server.conf --tls-cert /home/kasahara/.config/Deskflow/tls/deskflow.pem
[2025-01-20T09:44:10] INFO: using legacy x windows screen
[2025-01-20T09:44:10] WARNING: failed to open /usr/share/X11/xkb/rules/evdev.xml
[2025-01-20T09:44:10] WARNING: language "us" is unknown
```

### Additional information

I applied the following patch locally to solve the problem.
```
diff --git a/src/lib/deskflow/unix/AppUtilUnix.cpp b/src/lib/deskflow/unix/AppUtilUnix.cpp
index 87836cbe..7ce40a3c 100644
--- a/src/lib/deskflow/unix/AppUtilUnix.cpp
+++ b/src/lib/deskflow/unix/AppUtilUnix.cpp
@@ -65,7 +65,7 @@ std::vector<std::string> AppUtilUnix::getKeyboardLayoutList()
   std::vector<std::string> layoutLangCodes;
 
 #if WINAPI_XWINDOWS
-  layoutLangCodes = X11LayoutsParser::getX11LanguageList("/usr/share/X11/xkb/rules/evdev.xml");
+  layoutLangCodes = X11LayoutsParser::getX11LanguageList("/usr/local/share/X11/xkb/rules/evdev.xml");
 #elif WINAPI_CARBON
   CFStringRef keys[] = {kTISPropertyInputSourceCategory};
   CFStringRef values[] = {kTISCategoryKeyboardInputSource};
@@ -146,7 +146,7 @@ std::string AppUtilUnix::getCurrentLanguageCode()
   XFree(kbdDescr);
   XCloseDisplay(display);
 
-  result = X11LayoutsParser::convertLayotToISO("/usr/share/X11/xkb/rules/evdev.xml", result);
+  result = X11LayoutsParser::convertLayotToISO("/usr/local/share/X11/xkb/rules/evdev.xml", result);
 
 #elif WINAPI_CARBON
   auto layoutLanguages =

```
The server log after the patch:
```
[2025-01-20T09:50:04] INFO: starting core server process (desktop mode)
[2025-01-20T09:50:05] INFO: core config file: /home/kasahara/.config/Deskflow/deskflow-server.conf
[2025-01-20T09:50:05] INFO: running command: /usr/home/kasahara/src/deskflow/build/bin/deskflow-server -f --no-tray --debug INFO --name elvenbow --enable-crypto --address :24800 -c /home/kasahara/.config/Deskflow/deskflow-server.conf --tls-cert /home/kasahara/.config/Deskflow/tls/deskflow.pem
[2025-01-20T09:50:05] INFO: using legacy x windows screen
[2025-01-20T09:50:05] NOTE: started server, waiting for clients
[2025-01-20T09:50:05] INFO: accepted secure socket
[2025-01-20T09:50:05] INFO: network encryption protocol: TLSv1.3
[2025-01-20T09:50:05] NOTE: accepted client connection
[2025-01-20T09:50:05] INFO: local languages: en
```

### PR DESCRIPTION
**Pull request by sithlord48**
Fixed based on #8112 for bsd users

### CODE REVIEW

File: src/lib/deskflow/unix/AppUtilUnix.cpp [hunk 1]
```diff
@@ -65,7 +66,11 @@ std::vector<std::string> AppUtilUnix::getKeyboardLayoutList()
   std::vector<std::string> layoutLangCodes;
 
 #if WINAPI_XWINDOWS
-  layoutLangCodes = X11LayoutsParser::getX11LanguageList("/usr/share/X11/xkb/rules/evdev.xml");
+  m_evdev = "/usr/local/share/X11/xkb/rules/evdev.xml";
+  if (!std::filesystem::exists(m_evdev))
+    m_evdev = "/usr/share/X11/xkb/rules/evdev.xml";
+  layoutLangCodes = X11LayoutsParser::getX11LanguageList(m_evdev);
```
Comment (nbolton) [inline src/lib/deskflow/unix/AppUtilUnix.cpp:72]: Please add a comment here explaining to future devs why a fallback path is needed here.

**Review by nbolton — CHANGES_REQUESTED** [review]

File: src/lib/deskflow/unix/AppUtilUnix.cpp (hunk 1 above)
Comment (sithlord48) [reply src/lib/deskflow/unix/AppUtilUnix.cpp:73]: done.
