### PR TITLE
Fix: Screen icons not showing on the screen setup tab

### LINKED ISSUE #8155: Screens icons do not show on server config layout editor
### Project

Deskflow

### Deskflow version number

1.18.x

### Build type

Local developer build (built it myself)

### OS versions/distros

Any

### Deskflow configuration

_No response_

### What steps will reproduce the problem?

1. Open GUI
2. Click 'Configure'

Expect: Screen icons in each grid cell
Actual: Only text

### Log output

```shell

```

### Additional information

This happened when we upgraded from Qt5 to Qt6 and I hadn't gotten round to reporting it yet.

How it used to look when it was working:
Image

### PR DESCRIPTION
**Pull request by sithlord48**
- Fix #8155 
 - "Return Early Return Often"  in `ScreenSetupModel::data method`
 -  Bring back the `NewScreenWidget`
 -  `QTextStream& screen::writeScreensSection(QTextStream&)` -> `QString Screen::screenSection()`
 -  `QTextStream& screen::writeAliasSection(QTextStream&)` -> `QString Screen::aliasSection()`

### CODE REVIEW

File: src/apps/deskflow-gui/widgets/ScreenSetupView.cpp [hunk 1]
```diff
@@ -140,8 +148,16 @@ void ScreenSetupView::startDrag(Qt::DropActions)
...
+  option->initFrom(w);
+  w->deleteLater();
+  delete w;
+
+  option->decorationSize = QSize(96, 96);
   option->showDecorationSelected = true;
   option->decorationPosition = QStyleOptionViewItem::Top;
-  option->displayAlignment = Qt::AlignCenter;
+  option->decorationAlignment = Qt::AlignHCenter | Qt::AlignVCenter;
+  option->displayAlignment = Qt::AlignBottom | Qt::AlignHCenter;
```
Comment (nbolton) [inline src/apps/deskflow-gui/widgets/ScreenSetupView.cpp:161]: Align top looks neater.
```suggestion
  option->displayAlignment = Qt::AlignTop | Qt::AlignHCenter;
```

Before:
image

After:
Screenshot From 2025-01-30 12-42-10

File: src/apps/deskflow-gui/widgets/NewScreenWidget.cpp [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+{
+}
+
+void NewScreenWidget::mousePressEvent(QMouseEvent *event)
+{
+  Screen newScreen(tr("Unnamed"));
+
+  QByteArray itemData;
+  QDataStream dataStream(&itemData, QIODevice::WriteOnly);
+  dataStream << -1 << -1 << newScreen;
```
Comment (nbolton) [inline src/apps/deskflow-gui/widgets/NewScreenWidget.cpp:27]: This would benefit from a comment as it's a little mysterious: `<< -1 << -1 <<`

File: src/apps/deskflow-gui/widgets/NewScreenWidget.cpp [hunk 3]
```diff
@@ -0,0 +1,37 @@
+/*
+ * Deskflow -- mouse and keyboard sharing utility
+ * SPDX-FileCopyrightText: (C) 2025 Deskflow Developers
+ * SPDX-FileCopyrightText: (C) 2012 - 2016 Symless Ltd.
+ * SPDX-FileCopyrightText: (C) 2008 Volker Lanz <vl@fidra.de>
```
Comment (nbolton) [inline src/apps/deskflow-gui/widgets/NewScreenWidget.cpp:5]: Not needed, unless some code was copied? Looks like new code.
```suggestion
```

File: src/apps/deskflow-gui/widgets/NewScreenWidget.h [hunk 4]
```diff
@@ -0,0 +1,24 @@
+/*
+ * Deskflow -- mouse and keyboard sharing utility
+ * SPDX-FileCopyrightText: (C) 2012 - 2016 Symless Ltd.
+ * SPDX-FileCopyrightText: (C) 2008 Volker Lanz <vl@fidra.de>
```
Comment (nbolton) [inline src/apps/deskflow-gui/widgets/NewScreenWidget.h:4]:
```suggestion
 * SPDX-FileCopyrightText: (C) 2025 Deskflow Developers
```

File: src/lib/gui/config/Screen.cpp
Comment (nbolton) [inline src/lib/gui/config/Screen.cpp:1]: Nice refactoring.

**Review by nbolton — CHANGES_REQUESTED** [review]
Amazing, how did you fix the disabled screen problem? I can't spot the difference from what you showed me last night.

File: src/apps/deskflow-gui/widgets/NewScreenWidget.cpp (hunk 3 above)
Comment (sithlord48) [reply src/apps/deskflow-gui/widgets/NewScreenWidget.cpp:5]: This is old code re added.

File: src/apps/deskflow-gui/widgets/NewScreenWidget.h (hunk 4 above)
Comment (sithlord48) [reply src/apps/deskflow-gui/widgets/NewScreenWidget.h:4]: I didn't make any changes to this file so not copyright update for it

File: src/apps/deskflow-gui/widgets/NewScreenWidget.cpp (hunk 2 above)
Comment (sithlord48) [reply src/apps/deskflow-gui/widgets/NewScreenWidget.cpp:27]: This code is old code that was reintroduced. Not sure the intent of this.

**Comment by sithlord48** [comment]
> Amazing, how did you fix the disabled screen problem? I can't spot the difference from what you showed me last night.

I fixed the QStyleViewItem optiions to a basic widget then customized it.. not sure what key was previously missing from the options so just started w/ a known good then modified. Before it was empty and we only set the few keys we used.

**Review by nbolton — APPROVED** [review]
Looks great!
