### PR TITLE
fixes #8463 do not assume C for root

### LINKED ISSUE #8463: failed to open core config file for write: C:/ProgramData/Deskflow/deskflow-server.conf With os installed to D
### Project

Deskflow

### Deskflow version info

v1.21.2.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [x] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

win11

### Deskflow configuration

_No response_

### What steps will reproduce the problem?

failed to open core config file for write: C:/ProgramData/Deskflow/deskflow-server.conf
My PC's system disk is D:/ other than C:/

### Log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sithlord48**
When we moved the settings we assumed C we need to use QDir::rootPath in the case of windows not being installed on the "C" drive.

### CODE REVIEW

File: src/lib/common/Settings.h [hunk 1]
```diff
@@ -20,7 +20,7 @@ class Settings : public QObject
 public:
 #if defined(Q_OS_WIN)
   inline const static auto UserDir = QStringLiteral("%1/AppData/Local/%2").arg(QDir::homePath(), kAppName);
-  inline const static auto SystemDir = QStringLiteral("C:/ProgramData/%1").arg(kAppName);
+  inline const static auto SystemDir = QStringLiteral("%1ProgramData/%2").arg(QDir::rootPath(), kAppName);
```
Comment (nbolton) [inline src/lib/common/Settings.h:23]: I wonder if using `QStandardPaths::standardLocations(QStandardPaths::AppConfigLocation)` might be better?

```
// includes
#include <QDebug>
#include <QString>
#include <QStandardPaths>
#include <QDir>

// code
QString configDataDirString = QStandardPaths::standardLocations(QStandardPaths::AppConfigLocation).at(1);
QDir dir(configDataDirString); // "C:/ProgramData/<APPNAME>"
dir.cdUp(); // cd ..
qDebug() << dir.path(); // "C:/ProgramData"
```
Source: https://forum.qt.io/topic/103227/how-to-get-windows-programdata-location/4?_=1744191273515&lang=en-US

Comment (sithlord48) [reply src/lib/common/Settings.h:23]: No app config location will look in user/appdata first. then system .

Comment (nbolton) [reply src/lib/common/Settings.h:23]: OK will test and review as is.

**Review by nbolton — APPROVED** [review]
