### PR TITLE
Address switch Corner issues.

### LINKED ISSUE #8231: Setting dead corners breaks server config
### Project

Deskflow

### Deskflow version number

1.19.0.68
Last worked on 1.18.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [ ] macOS
- [ ] Linux (X11)
- [x] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [x] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [x] I am not using macOS

### Continuous build

- [x] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Arch Linux

### Deskflow configuration

N/A to this bug. 

### What steps will reproduce the problem?

Enable a dead corner.

### Log output

```shell
[2025-02-19T15:14:02] ERROR: cannot read configuration "/home/chris/.config/Deskflow/deskflow-server.conf": read error: line 14: invalid argument "none+bottom-left"
[2025-02-19T15:14:02] FATAL: deskflow-server: failed to load config: /home/chris/.config/Deskflow/deskflow-server.conf
```

### Additional information

_No response_

### LINKED ISSUE #8276: Switch Corners are reset on app load
### Project

Deskflow

### Deskflow version info
Every version i tested.
i was able to try Deskflow from 1.17.1 - 1.19.0.155
Its possible this issue predates 1.17.1

### What steps will reproduce the problem?

Set some corners in the settings
Note the change in your settings file to switchCorners.
close deskflow 
open deskflow 
Note the reset for the switchCorners.

### Additional information

The settings are saved until you restart the app ,
crash when set has reported also #8231

### PR DESCRIPTION
**Pull request by sithlord48**
Resolve issues related to the `switchCorners` setting

- [X] fixes #8231
- [x] fixes #8276

### CODE REVIEW

File: src/lib/gui/config/Screen.cpp [hunk 1]
```diff
@@ -90,12 +90,13 @@ QString Screen::screensSection() const
   for (int i = 0; i < fixes().size(); i++)
     out.append(lineTemplate.arg(fixName(i), fixes().at(i) ? QStringLiteral("true") : QStringLiteral("false")));
 
-  out.append(QStringLiteral("\t\tswitchCorners = none"));
-  for (int i = 0; i < switchCorners().size(); i++)
+  auto corners = QStringLiteral("none");
+  for (int i = 0; i < switchCorners().size(); i++) {
     if (switchCorners()[i])
-      out.append(QStringLiteral("+%1 ").arg(switchCornerName(i)));
+      corners.append(QStringLiteral(" +%1 ").arg(switchCornerName(i)));
```
Comment (nbolton) [inline src/lib/gui/config/Screen.cpp:96]: The extra space char at the end doesn't seem to be needed.
```suggestion
      corners.append(QStringLiteral(" +%1").arg(switchCornerName(i)));
```

**Review by nbolton — APPROVED** [review]

File: src/lib/gui/config/Screen.cpp (hunk 1 above)
Comment (sithlord48) [reply src/lib/gui/config/Screen.cpp:96]: This fixes the parsing .... without it crashes...

Comment (nbolton) [reply src/lib/gui/config/Screen.cpp:96]: I don't think so. It appears the fix is to move the space from right to left. The extra space at the end isn't really needed. I tried with just the left space and it works fine.

Comment (nbolton) [reply src/lib/gui/config/Screen.cpp:96]: Decision on Matrix: Leave the extra space in and @sithlord48 will remove it later.

**Review by nbolton — APPROVED** [review]
